// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfcEwJHroUU1Q0GP7DieFlijnK4To9K8',
    appId: '1:703570850428:web:fb486b430d571865948ff9',
    messagingSenderId: '703570850428',
    projectId: 'login-fd4e2',
    authDomain: 'login-fd4e2.firebaseapp.com',
    storageBucket: 'login-fd4e2.firebasestorage.app',
    measurementId: 'G-66YXZJNWZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1X6230mRCExgjTHQ5STHNiak-RP84to',
    appId: '1:703570850428:android:9106cdc598bcef66948ff9',
    messagingSenderId: '703570850428',
    projectId: 'login-fd4e2',
    storageBucket: 'login-fd4e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtlxY4TV31-WgMualdS3V-DSB0JuhJVoM',
    appId: '1:703570850428:ios:3dec003f07c2c96f948ff9',
    messagingSenderId: '703570850428',
    projectId: 'login-fd4e2',
    storageBucket: 'login-fd4e2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtlxY4TV31-WgMualdS3V-DSB0JuhJVoM',
    appId: '1:703570850428:ios:3dec003f07c2c96f948ff9',
    messagingSenderId: '703570850428',
    projectId: 'login-fd4e2',
    storageBucket: 'login-fd4e2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZfcEwJHroUU1Q0GP7DieFlijnK4To9K8',
    appId: '1:703570850428:web:2b6353a2552f98a9948ff9',
    messagingSenderId: '703570850428',
    projectId: 'login-fd4e2',
    authDomain: 'login-fd4e2.firebaseapp.com',
    storageBucket: 'login-fd4e2.firebasestorage.app',
    measurementId: 'G-YMLR6KCGJ9',
  );
}
